Repository JCSDA/jedi-stack, pull requests merged in 2020-09, with the labels that each got.

#137 Feature/ncep bufr
  buildscripts/build_stack.sh
  buildscripts/libs/build_bufrlib.sh
  modulefiles/apps/jedi/gnu-openmpi.lua
  modulefiles/apps/jedi/intel-impi.lua
  modulefiles/compiler/compilerName/compilerVersion/bufrlib/bufrlib.lua
Labels: JEDI1

#128 Add gsl to the build_stack.sh process.
  buildscripts/build_stack.sh
  buildscripts/config/config_cheyenne.sh
  buildscripts/config/config_container-clang-mpich-dev.sh
  buildscripts/config/config_container-gnu-openmpi-dev.sh
  buildscripts/config/config_container-intel-impi-dev.sh
  buildscripts/config/config_custom.sh
  buildscripts/config/config_gentoo.sh
  buildscripts/config/config_mac.sh
  buildscripts/config/config_orion.sh
  buildscripts/config/config_rhel7emc.sh
  buildscripts/libs/build_gsl_lite.sh
  modulefiles/core/gsl_lite/gsl_lite.lua
Labels: JEDI2

#140 Feature/macos gfortran updates
  buildscripts/libs/build_mpi.sh
  buildscripts/libs/build_pnetcdf.sh
  buildscripts/setup_modules.sh
Labels: JEDI1, enhancement

#145 Add control for selecting the build of the gsl-lite package
  buildscripts/config/choose_modules.sh
  modulefiles/apps/jedi/clang-mpich.lua
  modulefiles/apps/jedi/clang-openmpi.lua
Labels: JEDI1, bug

#150 Update Platforms.md
  doc/Platforms.md
Labels: JEDI1, documentation

#158 initial commit: update to provide a clean build directory
  buildscripts/libs/build_bufrlib.sh
Labels: JEDI1, bug

#156 initial commit: flags to support GNU 10 compilers
  buildscripts/libs/build_nccmp.sh
  buildscripts/libs/build_pio.sh
Labels: JEDI1, enhancement

#160 add FMS to the stack
  README.md
  buildscripts/build_stack.sh
  buildscripts/config/choose_modules.sh
  buildscripts/config/config_container-clang-mpich-dev.sh
  buildscripts/config/config_container-gnu-openmpi-dev.sh
  buildscripts/config/config_container-intel-impi-app.sh
  buildscripts/config/config_container-intel-impi-dev.sh
  buildscripts/libs/build_fms.sh
  modulefiles/mpi/compilerName/compilerVersion/mpiName/mpiVersion/fms/fms.lua
Labels: enhancement
